CREATE DATABASE IF NOT EXISTS `eteldb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `eteldb`;

CREATE TABLE `etelek` (
  `id` int(11) AUTO_INCREMENT PRIMARY KEY,
  `nev` varchar(255) NOT NULL,
  `kaloria` int(11) NOT NULL,
  `etkezes_típus` varchar(50) DEFAULT NULL,
  `recept_link` varchar(255) DEFAULT NULL
)

INSERT INTO `etelek` (`nev`, `kaloria`, `etkezes_típus`, `recept_link`) VALUES
('Zöldséges csirkeragu', 450, 'Ebéd', 'https://www.nosalty.hu/recept/zoldseges-csirkeragu'),
('Rakott krumpli', 600, 'Ebéd', 'https://www.nosalty.hu/recept/rakott-krumpli'),
('Zöldségfasírt', 250, 'Vacsora', 'https://www.nosalty.hu/recept/zoldsegfasirt'),
('Túrós csusza', 700, 'Ebéd', 'https://www.nosalty.hu/recept/turos-csusza'),
('Szilvás gombóc', 400, 'Desszert', 'https://www.nosalty.hu/recept/szilvas-gomboc'),
('Cézár saláta', 350, 'Ebéd', 'https://www.nosalty.hu/recept/cezar-salata'),
('Káposztás tészta', 550, 'Ebéd', 'https://www.nosalty.hu/recept/kaposztas-teszta'),
('Hummusz', 200, 'Snack', 'https://www.nosalty.hu/recept/hummusz'),
('Almás pité', 350, 'Desszert', 'https://www.nosalty.hu/recept/almas-pite'),
('Gulyásleves', 700, 'Ebéd', 'https://www.nosalty.hu/recept/gulyasleves'),
('Sült édesburgonya', 200, 'Vacsora', 'https://www.nosalty.hu/recept/sult-edesburgonya'),
('Avokádó saláta', 250, 'Snack', 'https://www.nosalty.hu/recept/avokado-salata'),
('Pikáns csirkeszárnyak', 400, 'Vacsora', 'https://www.nosalty.hu/recept/pikans-csirkeszarnyak'),
('Lazacos spagetti', 500, 'Ebéd', 'https://www.nosalty.hu/recept/lazacos-spagetti'),
('Kínai tojásos rizs', 400, 'Ebéd', 'https://www.nosalty.hu/recept/kínai-tojásos-rizs'),
('Túrós rakott palacsinta', 400, 'Desszert', 'https://www.nosalty.hu/recept/turos-rakott-palacsinta'),
('Fasírt', 300, 'Ebéd', 'https://www.nosalty.hu/recept/fasirt'),
('Tojásos nokedli', 400, 'Ebéd', 'https://www.nosalty.hu/recept/tojasos-nokedli'),
('Sajtos túrós pogácsa', 250, 'Snack', 'https://www.nosalty.hu/recept/sajtos-turos-pogacsa'),
('Paradicsomos rakott tészta', 650, 'Ebéd', 'https://www.nosalty.hu/recept/paradicsomos-rakott-teszta'),
('Fűszeres csirkecomb', 450, 'Vacsora', 'https://www.nosalty.hu/recept/fuszeres-csirkecomb'),
('Csokis muffin', 400, 'Desszert', 'https://www.nosalty.hu/recept/csokis-muffin'),
('Francia hagymaleves', 350, 'Vacsora', 'https://www.nosalty.hu/recept/francia-hagymaleves'),
('Körtés pite', 400, 'Desszert', 'https://www.nosalty.hu/recept/kortes-pite'),
('Pizzás csiga', 350, 'Snack', 'https://www.nosalty.hu/recept/pizzas-csiga'),
('Tejfölös burgonya', 400, 'Vacsora', 'https://www.nosalty.hu/recept/tejfolos-burgonya'),
('Töltött káposzta', 700, 'Ebéd', 'https://www.nosalty.hu/recept/toltott-kaposzta'),
('Reggeli burrito',890,'Reggeli','https://www.nosalty.hu/recept/reggeli-burrito'),
('Brit reggeli',1110,'Reggeli','https://www.nosalty.hu/recept/brit-reggeli'),
('Reggeli wrap',330,'Reggeli','https://www.nosalty.hu/recept/reggeli-wrap'),
('Reggeli chia pudding',290,'Reggeli','https://www.nosalty.hu/recept/reggeli-chia-puding'),
('Fahéjas-szilvás fogyis reggeli',240,'Reggeli','https://www.nosalty.hu/recept/fahejas-szilvas-fogyis-reggeli'),
('Villásreggeli Twin Peaks-ből',450,'Reggeli','https://www.nosalty.hu/recept/villasreggeli-twin-peaks-bol'),
('Zabkása reggeli',570,'Reggeli','https://www.nosalty.hu/recept/zabkasa-reggelire'),
('Ropogós rántott karfiol',360,'Vacsora','https://www.nosalty.hu/recept/ropogos-rantott-karfiol'),
('Húsos burrito',860,'Vacsora','https://www.nosalty.hu/recept/husos-burrito'),
('Hagymás bab wstern módra',480,'Vacsora','https://www.nosalty.hu/recept/hagymas-bab'),
('Nizzai pizza',270,'Vacsora','https://www.nosalty.hu/recept/nizzai-lepeny-pissaladiere'),
('Mexikói csirkés egytál',600,'Vacsora','https://www.nosalty.hu/recept/mexikoi-csirkes-egytal'),
('Fűszeres sajtgolyók',320,'Vacsora','https://www.nosalty.hu/recept/fuszeres-sajtgolyok-detki-gourmet-keker-kekszmorzsa-curry-hagyma-vital-fitt');
